new registration and login scenario using API
matty-team/matty-android-app pull request #1
Opened 2022-08-19 17:39 UTC by Nikknik

1. Use Matty API for login and registration
2. Get current user from Matty API
3. Cache user in Shared Prefs
4. Some refactoring

2022-08-23 16:29 UTC, solid0x commented on app/src/main/java/com/matryoshka/projectx/Constants.kt
> +    const val SEND_REGISTER_CODE_PATH = "registration/code"
```suggestion
    const val REGISTER_CODE_PATH = "registration/code"
```
Я бы не стал добавлять действие в название эндпоинта
По этой точке мог бы также находится метод для рефреша кода с query-параметром типа registration/code?refresh

2022-08-23 16:39 UTC, solid0x approved these changes
Осталось раз-два и в продакшн 😀

2022-08-23 16:39 UTC, solid0x commented on app/src/main/java/com/matryoshka/projectx/data/auth/TokensInfo.kt
> +data class TokensInfo(
```suggestion
data class TokenPair(
```
Как альтернатива )

2022-08-26 18:04 UTC, ShibaC0der commented on app/src/main/java/com/matryoshka/projectx/data/auth/TokensInfo.kt
> +data class TokensInfo(
Или AuthTokens

2022-08-26 20:53 UTC, ShibaC0der requested changes
Отличный PR, но есть небольшие вопросы. Посмотри, пожалуйста.

2022-08-26 20:53 UTC, ShibaC0der commented on app/src/main/java/com/matryoshka/projectx/data/cache/SharedPrefsCache.kt
> +    private val expiredPeriod: Long,
```suggestion
    private val lifeSpan: Duration
```
Если фундаментально, то посмотри java.time пакет:
https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/TimeUnit.html
https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html
Но так как мы пишем на Kotlin, можно использовать:
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.time/-duration/

`val lifeSpan = 30.seconds`

2022-08-26 20:53 UTC, ShibaC0der commented on app/src/main/java/com/matryoshka/projectx/data/cache/SharedPrefsCache.kt
> +enum class CacheExpireTimeUnit {
Писал выше про 🚲

2022-08-26 20:53 UTC, ShibaC0der commented on app/src/main/java/com/matryoshka/projectx/data/cache/SharedPrefsCache.kt
> +fun getExpiredPeriodInMillis(expiredPeriod: Long, expiredTimeUnit: CacheExpireTimeUnit): Long =
В этом не будет необходимости, когда заюзаешь Duration

2022-08-26 20:53 UTC, ShibaC0der commented on app/src/main/java/com/matryoshka/projectx/data/cache/SharedPrefsCache.kt
> +        val cacheContainer = Gson().fromJson(json, CacheContainer::class.java)
Может быть как-то можно избежать двойной десериализации ? 🙂
Как один из вариантов:
`data class CachedValue<out T>(
   val value: T,
   val expireTime: Long
)`

2022-08-26 20:53 UTC, ShibaC0der commented on app/src/main/java/com/matryoshka/projectx/data/cache/SharedPrefsCache.kt
> +        val json = context.sharedPreferences.getString(key, null)
Может стоит хранить по слабой ссылке внутри SharedPrefsCache значение после первой загрузки, а потом уже если ссылка ведет в null или время жизни закончилось, ходить в sharedPreferences или перезагружать?

2022-08-26 20:53 UTC, ShibaC0der commented on app/src/main/java/com/matryoshka/projectx/di/ApiClientModule.kt
> +private fun shouldRefreshTokens(response: HttpResponse): Boolean {
👍

2022-08-26 20:53 UTC, ShibaC0der commented on app/src/main/java/com/matryoshka/projectx/di/ApiClientModule.kt
> +        HttpStatusCode.Unauthorized -> throw UnauthorizedException(error)
static import

2022-08-26 20:53 UTC, ShibaC0der commented on app/src/main/java/com/matryoshka/projectx/data/user/MattyApiUsersRepository.kt
> +    private val client: HttpClient,
```suggestion
    private val httpClient: HttpClient,
```

2022-08-26 20:53 UTC, ShibaC0der commented on app/src/main/java/com/matryoshka/projectx/data/user/MattyApiUsersRepository.kt
> +                client.get(MattyApiPath.GET_CURRENT_USER_PATH).body<ApiUser>().toDomain()
```suggestion
                httpClient.get(MattyApiPath.GET_CURRENT_USER_PATH).body<ApiUser>().toDomain()
```

2022-08-26 20:53 UTC, ShibaC0der commented on app/src/main/java/com/matryoshka/projectx/di/ApiClientModule.kt
> +                            //to avoid hanging on repeated 401
Реализация четкая! Кстати, как вариант, ты мог сделать два клиента: httpClient(protected) и publicHttpClient

2022-08-26 20:53 UTC, ShibaC0der commented on app/src/main/java/com/matryoshka/projectx/di/ApiClientModule.kt
> +                            //to avoid hanging on repeated 401
Причем publicHttpClient был бы ViewModelScope

2022-08-26 20:53 UTC, ShibaC0der commented on app/src/main/java/com/matryoshka/projectx/di/ApiClientModule.kt
> +                            //to avoid hanging on repeated 401
+  а если refresh_token тухлый, то не зависает?

2022-08-26 20:53 UTC, ShibaC0der commented on app/src/main/java/com/matryoshka/projectx/exception/HttpExceptions.kt
> +    val timestamp: DateTime,
Почему не из java.time ?

2022-08-26 20:53 UTC, ShibaC0der commented on app/src/main/java/com/matryoshka/projectx/navigation/NavActions.kt
> +        val gson = GsonBuilder().registerAdapters().create()
почему не buildGson(), кстати, а Gson instance не reusable ?

2022-08-26 20:53 UTC, ShibaC0der commented on app/src/main/java/com/matryoshka/projectx/service/AuthService.kt
> +    suspend fun sendRegistrationCodeToEmail(email: String): Instant
```suggestion
    suspend fun sendRegistrationCode(email: String): Instant
```

2022-08-26 20:53 UTC, ShibaC0der commented on app/src/main/java/com/matryoshka/projectx/service/AuthService.kt
> +    suspend fun sendLoginCodeToEmail(email: String): Instant
```suggestion
    suspend fun sendLoginCode(email: String): Instant
```

2022-08-26 20:53 UTC, ShibaC0der commented on app/src/main/java/com/matryoshka/projectx/service/MattyApiAuthService.kt
> +            Log.d(TAG, "$methodName: $result")
```suggestion
            Log.d(TAG, "$SEND_REGISTER_CODE_PATH: $result")
```

2022-08-26 20:53 UTC, ShibaC0der commented on app/src/main/java/com/matryoshka/projectx/service/MattyApiAuthService.kt
> +        val methodName = "sendRegistrationCodeToEmail"
```suggestion
```

2022-08-26 20:53 UTC, ShibaC0der commented on app/src/main/java/com/matryoshka/projectx/service/MattyApiAuthService.kt
> +    private val client: HttpClient,
```suggestion
    private val httpClient: HttpClient,
```

2022-08-26 20:53 UTC, ShibaC0der commented on app/src/main/java/com/matryoshka/projectx/navigation/AppNavGraph.kt
> +            buildGson().fromJson(json, Event::class.java)
Попробуй залогировать вызов. Я думаю, что из-за сайд эффектов компоуза (недетерминированных рекомпозиций) этот кусок будет вызываться чаще, чем ты ожидаешь 🙂

2022-08-26 20:53 UTC, ShibaC0der commented on app/src/main/java/com/matryoshka/projectx/ui/common/XShaker.kt
> +fun XShaker(
🧑‍💻

2022-09-04 23:14 UTC, Nikknik commented on app/src/main/java/com/matryoshka/projectx/Constants.kt
> +    const val SEND_REGISTER_CODE_PATH = "registration/code"
Исправил

2022-09-04 23:14 UTC, Nikknik commented on app/src/main/java/com/matryoshka/projectx/data/auth/TokensInfo.kt
> +data class TokensInfo(
Исправил

2022-09-04 23:14 UTC, Nikknik commented on app/src/main/java/com/matryoshka/projectx/data/cache/SharedPrefsCache.kt
> +    private val expiredPeriod: Long,
Исправил

2022-09-04 23:15 UTC, Nikknik commented on app/src/main/java/com/matryoshka/projectx/data/cache/SharedPrefsCache.kt
> +        val cacheContainer = Gson().fromJson(json, CacheContainer::class.java)
Исправил. Пришлось поэкспериментировать)

2022-09-04 23:16 UTC, Nikknik commented on app/src/main/java/com/matryoshka/projectx/data/cache/SharedPrefsCache.kt
> +        val json = context.sharedPreferences.getString(key, null)
Сделал. Спасибо за идею 🙂

2022-09-04 23:16 UTC, Nikknik commented on app/src/main/java/com/matryoshka/projectx/di/ApiClientModule.kt
> +        HttpStatusCode.Unauthorized -> throw UnauthorizedException(error)
Исправил

2022-09-04 23:22 UTC, Nikknik commented on app/src/main/java/com/matryoshka/projectx/di/ApiClientModule.kt
> +                            //to avoid hanging on repeated 401
1. Пока нет надобности, решил оставить одного клиента
2. Все зависания вроде бы исправил)

2022-09-04 23:23 UTC, Nikknik commented on app/src/main/java/com/matryoshka/projectx/exception/HttpExceptions.kt
> +    val timestamp: DateTime,
Поторопился) Посмотрел, в каком формате ты сейчас ошибки возвращаешь и вообще убрал время

2022-09-04 23:23 UTC, Nikknik commented on app/src/main/java/com/matryoshka/projectx/navigation/NavActions.kt
> +        val gson = GsonBuilder().registerAdapters().create()
Исправил

2022-09-04 23:24 UTC, Nikknik commented on app/src/main/java/com/matryoshka/projectx/navigation/AppNavGraph.kt
> +            buildGson().fromJson(json, Event::class.java)
Действительно, вызывался лишние разы (

2022-09-04 23:24 UTC, Nikknik commented on app/src/main/java/com/matryoshka/projectx/ui/common/XShaker.kt
> +fun XShaker(
Переименовал)

2022-09-16 16:11 UTC, ShibaC0der approved these changes

2022-09-16 16:16 UTC, ShibaC0der approved these changes

2022-09-19 23:30 UTC, merged